### ISSUE TITLE
Ellis starts with wrong configuration

### ISSUE THREAD

**Issue by mike-evans** [Metaswitch/clearwater-docker#10]
Ellis can start with the wrong IP address configuration for Homestead and Homer.  Restarting Ellis fixes the problem.

It looks like the root cause is that supervisord does not guarantee that the clearwater-auto-config-docker and clearwater-infrastructure services are started prior to starting Ellis.  Since clearwater-auto-config-docker generates the configuration file, Ellis may start with the wrong configuration (likely the IP address assigned to the image when it is built).

It doesn't look like there is an easy fix to this in supervisord (eg. see http://stackoverflow.com/questions/17443692/python-supervisord-program-dependency).  It sounds like priority won't guarantee that the auto-config has completed before starting Ellis, and the recommendation is either to use an event listener or a wrapper shell script which only starts Ellis when the auto-config has completed.

**Comment by mirw** [comment]
I wonder if we can mark all processes as `autostart=false` and then run `supervisorctl start all` as the last command of the clearwater-infrastructure command line.

I'll try prototyping this tomorrow.

**Comment by mirw** [comment]
@mike-evans, I've fixed this under #11.  Please can you retest?
