### ISSUE TITLE
Error in script clearwater-auto-config-docker

### ISSUE THREAD

**Issue by darko182** [Metaswitch/clearwater-docker#12]
If environmental variable ZONE is not set, "home_domain" variable should be "example.com".
The error is in setting the variable "home_domain" at row 82 of the script "clearwater-auto-config-docker": there is a blank at both sides of "=" sign.
This ends up in having "home_domain" unset.

**Comment by mirw** [comment]
Thanks for raising this.  @mike-evans spotted this this morning too and fixed under https://github.com/Metaswitch/clearwater-infrastructure/pull/202.  Please can you confirm that the problem is now resolved?

**Comment by eleanor-merry** [comment]
I've confirmed that this was fixed
