### ISSUE TITLE
Could not add PSTN number 

### ISSUE THREAD

**Issue by heekof** [Metaswitch/clearwater-docker#27]
I am working on a VM ubuntu : 
Linux clearwater2 3.13.0-87-generic #133-Ubuntu SMP Tue May 24 18:32:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux 
I have followed the installation with docker compose. Everything seems OK. But when I want to add a new PSTN number, I have this error: 
Failed to update the server (see detailed diagnostics in developer console). Please refresh the page. 

In ellis the log : 

WARNING _base.py:163: 503 POST /accounts/TATA%40TITI.org/numbers/?cb=1fa846b0bfN4 (0.0.0.0): No available numbers
30-08-2016 13:18:20.420 UTC ERROR web.py:1447: 503 POST /accounts/TATA%40TITI.org/numbers/?cb=1fa846b0bfN4 (0.0.0.0) 13.87ms

in sprout : 

Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL]):

In homer : 
    Sending 200 response to localhost for PUT http://http_homer/org.etsi.ngn.simservs/users/sip%3A6505550170%40example.com/simservs.xml

in homestead : 
UTC Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL])

**Comment by richardwhiuk** [comment]
By default the Docker deployment doesn't create any PSTN numbers. This is controlled by https://github.com/Metaswitch/clearwater-docker/blob/master/ellis/Dockerfile

If you want to create some PSTN numbers, you can use the create_numbers.py script to which you'll need to pass --pstn or -p to.

The difference between PSTN and internal numbers is described at https://github.com/Metaswitch/ellis/blob/stable/docs/features.md

There's details about doing this manually at http://clearwater.readthedocs.io/en/stable/Manual_Install.html#provision-telephone-numbers-in-ellis

**Comment by eleanor-merry** [comment]
Closing as answered.
