### ISSUE TITLE
build bono docker images error

### ISSUE THREAD

**Issue by apachemycat** [Metaswitch/clearwater-docker#32]
When I build bono images, there are some errors ,mainly the tcp kenel params change cmd cause ,which in file 
/usr/share/clearwater/infrastructure/install/clearwater-tcp-scalability.postinst

docker can't allowed this tcp kenel params be set in docker container 
is there any method to  Comment out clearwater-tcp-scalability.postinst file content  so  success file build ?
the following is error message 

Unpacking bono (1.0-160927.112438) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up libpci3:amd64 (1:3.2.1-1ubuntu5.1) ...
Setting up libboost-system1.54.0:amd64 (1.54.0-4ubuntu3.1) ...
Setting up libboost-filesystem1.54.0:amd64 (1.54.0-4ubuntu3.1) ...
Setting up libicu52:amd64 (52.1-3ubuntu0.4) ...
Setting up libboost-regex1.54.0:amd64 (1.54.0-4ubuntu3.1) ...
Setting up libboost-thread1.54.0:amd64 (1.54.0-4ubuntu3.1) ...
Setting up libevent-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
Setting up libevent-core-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
Setting up libevent-pthreads-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
Setting up libperl5.18 (5.18.2-2ubuntu1.1) ...
Setting up libsnmp-base (5.7.2~dfsg-clearwater4) ...
Setting up libsnmp30:amd64 (5.7.2~dfsg-clearwater4) ...
Setting up clearwater-tcp-scalability (1.0-160927.094809) ...
/usr/share/clearwater/infrastructure/install/clearwater-tcp-scalability.postinst: 40: /usr/share/clearwater/infrastructure/install/clearwater-tcp-scalability.postinst: sysctl: Permission denied
Setting up clearwater-log-cleanup (1.0-160927.094809) ...
dpkg: error processing package clearwater-tcp-scalability (--configure):
 subprocess installed post-installation script returned error exit status 126
Setting up sprout-libs (1.0-160927.112438) ...
Setting up clearwater-socket-factory (1.0-160927.094809) ...
dpkg: dependency problems prevent configuration of bono:
 bono depends on clearwater-tcp-scalability; however:
  Package clearwater-tcp-scalability is not configured yet.

dpkg: error processing package bono (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 clearwater-tcp-scalability
 bono
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes bono' returned a non-zero code: 100

**Comment by MatMeredith** [comment]
@apachemycat.   Looks like the same issue as #35.
