### ISSUE TITLE
build sprout docker image error 

### ISSUE THREAD

**Issue by apachemycat** [Metaswitch/clearwater-docker#35]
when I build sprout docker image ,there are more errors  and I found it try install memcache ,but memcache also a new clearwater image ??

the following is error msgs 
Setting up clearwater-tcp-scalability (1.0-160927.094809) ...
/usr/share/clearwater/infrastructure/install/clearwater-tcp-scalability.postinst: 40: /usr/share/clearwater/infrastructure/install/clearwater-tcp-scalability.postinst: sysctl: Permission denied
Setting up clearwater-log-cleanup (1.0-160927.094809) ...
dpkg: error processing package clearwater-tcp-scalability (--configure):
 subprocess installed post-installation script returned error exit status 126
Setting up astaire-libs (1.0-160927.103550) ...
Setting up cpulimit (2.0-1) ...
Setting up libc-ares-dev:amd64 (1.10.0-2) ...
dpkg: dependency problems prevent configuration of astaire:
 astaire depends on clearwater-tcp-scalability; however:
  Package clearwater-tcp-scalability is not configured yet.

dpkg: error processing package astaire (--configure):
 dependency problems - leaving unconfigured
Setting up snmp (5.7.2~dfsg-clearwater4) ...
Setting up snmpd (5.7.2~dfsg-clearwater4) ...
update-rc.d: warning:  stop runlevel arguments (1) do not match snmpd Default-Stop values (0 1 6)
invoke-rc.d: policy-rc.d denied execution of start.

Restarting memcached: memcached.
Setting up clearwater-memcached (1.0-160927.094809) ...
invoke-rc.d: policy-rc.d denied execution of start.
Setting up clearwater-socket-factory (1.0-160927.094809) ...
Setting up sprout-libs (1.0-160927.112438) ...
Processing triggers for ureadahead (0.100.0-16) ...
dpkg: dependency problems prevent configuration of sprout-base:
 sprout-base depends on clearwater-tcp-scalability; however:
  Package clearwater-tcp-scalability is not configured yet.
 sprout-base depends on astaire; however:
  Package astaire is not configured yet.

dpkg: error processing package sprout-base (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of sprout-scscf:
 sprout-scscf depends on sprout-base; however:
  Package sprout-base is not configured yet.

dpkg: error processing package sprout-scscf (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of sprout-icscf:
 sprout-icscf depends on sprout-base; however:
  Package sprout-base is not configured yet.

dpkg: error processing package sprout-icscf (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of sprout-bgcf:
 sprout-bgcf depends on sprout-base; however:
  Package sprout-base is not configured yet.

dpkg: error processing package sprout-bgcf (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of sprout-mmtel-as:
 sprout-mmtel-as depends on sprout-base; however:
  Package sprout-base is not configured yet.

dpkg: error processing package sprout-mmtel-as (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of sprout:
 sprout depends on sprout-base; however:
  Package sprout-base is not configured yet.
 sprout depends on sprout-scscf; however:
  Package sprout-scscf is not configured yet.
 sprout depends on sprout-icscf; however:
  Package sprout-icscf is not configured yet.
 sprout depends on sprout-bgcf; however:
  Package sprout-bgcf is not configured yet.
 sprout depends on sprout-mmtel-as; however:
  Package sprout-mmtel-as is not configured yet.

dpkg: error processing package sprout (--configure):
 dependency problems - leaving unconfigured

Setting up clearwater-snmpd (1.0-160927.094809) ...
- Stopping network management services:
  Setting up chronos (1.0-160927.094813) ...
  Setting up clearwater-snmp-handler-astaire (1.0-160927.112236) ...
- Stopping network management services:
  Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
  Processing triggers for ureadahead (0.100.0-16) ...
  Errors were encountered while processing:
  clearwater-tcp-scalability
  astaire
  sprout-base
  sprout-scscf
  sprout-icscf
  sprout-bgcf
  sprout-mmtel-as
  sprout
  E: Sub-process /usr/bin/dpkg returned an error code (1)
  The command '/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes sprout' returned a non-zero code: 100

**Comment by MatMeredith** [comment]
@apachemycat  We expect sysctl to fail inside Docker containers and so in our base Docker image we replace sysctl with a version that does nothing (see [base/sysctl](https://github.com/Metaswitch/clearwater-docker/blob/master/base/sysctl)).   The error you are seeing suggests to me that either this version of sysctl hasn't been correctly applied by [base/Dockerfile](https://github.com/Metaswitch/clearwater-docker/blob/master/base/Dockerfile), or that it has the wrong permissions.   Can you tell me more about the environment you are running in please and how you are building these images?
- Are you running on Linux or Windows?
- Have you modified the base Dockerfile at all?
- How have you attempted to build these images?
- What version of clearwater-docker have you checked out?

**Comment by apachemycat** [comment]
Thanks
I running  docker in Linux Centos 7 (64) VM  in VMware Player ,firstly kernel is 3.10 and lately updated to 4  (4.8.1-1.el7.elrepo.x86_64)
**[root@bogon ~]# docker version**
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

**I have no modified any docker buildfile ,your older docker  file also build and some errors the same (for example,sysctl  errror)**

I build this images use your command ：

# Build the Clearwater docker images.

cd clearwater-docker
for i in base memcached cassandra chronos bono ellis homer homestead ralf sprout ; do sudo docker build -t clearwater/$i $i ; done

**about 2 weeks ago ,I tried to build clearwater images ,also failed ,yesterday I find new version available ,so i  try to build again**

**I only successed the following images** 

[root@bogon ~]# docker images
REPOSITORY                                TAG                  IMAGE ID            CREATED             SIZE
clearwater/chronos                        latest               1c56eec809cd        3 hours ago         617.8 MB
clearwater/homer                          latest               8074ea964693        12 hours ago        811 MB
clearwater/ellis                          latest               51e96df270d3        13 hours ago        852.5 MB
clearwater/memcached                      latest               57282d2da872        13 hours ago        575.8 MB
clearwater/base                           latest               a0ba2081dc99        13 hours ago        569.5 MB

**Comment by MatMeredith** [comment]
@apachemycat Thanks for this, but it doesn't give me any more clues I'm afraid...   Could you try starting up a container using the clearwater/base image that you've successfully built and finding out what version of sysctl it contains please?   If you could provide the output of the following that would be great.

```
sudo docker run -d --name base -p 22 clearwater/base
sudo docker exec base which sysctl
sudo docker exec base ls -al /sbin/sysctl
ls -al base
```

(Last command needs to be run from the root of your clearwater-docker repo)

**Comment by apachemycat** [comment]
May be there's file execute permession wrong ? because I unziped git files in windows and copy them to VM 

**root@2a8862c5cefd:/# sysctl
bash: /sbin/sysctl: Permission denied**
root@2a8862c5cefd:/# whitch sysctl
root@2a8862c5cefd:/# which sysctl
root@2a8862c5cefd:/#  ls -al /sbin/sysctl
-rw-r--r-- 27 root root 38 Oct 11 19:16 /sbin/sysctl
**root@2a8862c5cefd:/# chmod +x /sbin/sysctl**
root@2a8862c5cefd:/# which sysctl
/sbin/sysctl
**root@2a8862c5cefd:/# ls -al base**
ls: cannot access base: No such file or directory

**Comment by apachemycat** [comment]
**Thanks for help** , I found  it's  the problem of unzip in windows cause file permission flags missing ,so build failed . now all images successful 

**but homestead has one problem ,following is the errmsg** 
   ...done.
/var/lib/dpkg/info/homestead-prov.postinst: 69: /var/lib/dpkg/info/homestead-prov.postinst: /usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh: not found

**Comment by apachemycat** [comment]
and I'm confused with your new docker run command ,--net-alias used for what purpose ?  in kubernetes the is no such ways ,how can i start it ?

@MatMeredith 
**But the name is bad in kubernetes ........**
Error from server: error when creating "k8s-clearwater.yaml": Service "icscf.sprout" is invalid: metadata.name: Invalid value: "icscf.sprout": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123')

**Comment by MatMeredith** [comment]
@apachemycat.   Great to hear that you've made progress on this.   
- You can just ignore the homestead build error -- it's harmless.
- The network-alias parameter when starting Sprout causes Docker to create DNS entries for the container so that it is reachable via icscf.sprout and scscf.sprout.   Bono (the P-CSCF) will route requests for the I-CSCF to icscf.sprout and the I-CSCF will route requests to the S-CSCF via scscf.sprout.   I believe that with Kubernetes the way this would work is that you would have Sprout pods and you would then configure Kubernetes "services" with names icscf.sprout and scscf.sprout that load balance across all of the Sprout pods.   Does that make sense?

Does that make sense?

**Comment by plwhite** [comment]
Worth saying that we have run clearwater in Kubernetes, but haven't really done anything with it in that environment. We'll be doing more in the next few weeks, I expect, at which point I'll have Kubernetes YAML files to share. I don't want to share them now, because while I have tested it all starts, I haven't tested that it can actually send load.

**Comment by apachemycat** [comment]
@MatMeredith ,Thanks for your help ,I will continue try to running clearwater  on Kubernetes .

**Comment by apachemycat** [comment]
@MatMeredith ，I saw .env used in bono container , if it means I can set PUBLIC_IP in runtime and not need to build into docker image ?
sudo docker run -d --net=clearwater_nw --name bono --env-file .env

**Comment by MatMeredith** [comment]
@apachemycat Yes, that's correct.

**Comment by mirw** [comment]
@MatMeredith, what's the next action here?  Is there an issue to fix, or should this be being closed down?

**Comment by MatMeredith** [comment]
I think this issue can be closed down, but @apachemycat please let me know if you think there is still a problem here and I'll reopen.
