### ISSUE TITLE
icscf.sprout and scscf.sprout host name maybe changed to icscf_sprout and scscf_sprout 

### ISSUE THREAD

**Issue by leader-us** [Metaswitch/clearwater-docker#38]
icscf.sprout and scscf.sprout host name maybe changed to icscf_sprout and scscf_sprout  
or use sprout name  ,because kuberntes can't create service which has '.' char in service name,
but I don't now where is config file in all related clearwater components.

**Comment by richardwhiuk** [comment]
We're looking into sharing suitable instructions for deploying clearwater-docker on Kubernetes shortly - we are aware of the issue with the alias not being compatible with Kubernetes.

We'd recommend the following suggestion, shared in https://github.com/Metaswitch/clearwater-docker/issues/35#issuecomment-253430862

> The network-alias parameter when starting Sprout causes Docker to create DNS entries for the container so that it is reachable via icscf.sprout and scscf.sprout. Bono (the P-CSCF) will route requests for the I-CSCF to icscf.sprout and the I-CSCF will route requests to the S-CSCF via scscf.sprout. I believe that with Kubernetes the way this would work is that you would have Sprout pods and you would then configure Kubernetes "services" with names icscf.sprout and scscf.sprout that load balance across all of the Sprout pods. Does that make sense?

**Comment by leader-us** [comment]
icscf.sprout used in which component , I can't find it ..

**Comment by richardwhiuk** [comment]
It's used by Sprout, both internally and externally. There's some work being done to support Kubernetes further on the kubernetes branch - https://github.com/Metaswitch/clearwater-docker/tree/kubernetes
