### ISSUE TITLE
bono can't connect agentx master agent 

### ISSUE THREAD

**Issue by leader-us** [Metaswitch/clearwater-docker#43]
19-10-2016 08:34:17.563 UTC Status alarm.cpp:62: sprout issued 1005.4 alarm
19-10-2016 08:34:20.056 UTC Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL]): 
19-10-2016 08:34:35.072 UTC Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL]): 
19-10-2016 08:34:47.564 UTC Status alarm.cpp:62: sprout issued 1005.4 alarm
19-10-2016 08:34:50.081 UTC Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL]): 
19-10-2016 08:34:53.858 UTC Status sip_connection_pool.cpp:447: Recycle TCP connection slot 21
19-10-2016 08:34:57.860 UTC Status sip_connection_pool.cpp:447: Recycle TCP connection slot 2
19-10-2016 08:35:02.863 UTC Status sip_connection_pool.cpp:447: Recycle TCP connection slot 29
19-10-2016 08:35:05.089 UTC Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL]): 
19-10-2016 08:35:17.564 UTC Status alarm.cpp:62: sprout issued 1005.4 alarm
19-10-2016 08:35:20.103 UTC Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL]): 
19-10-2016 08:35:35.117 UTC Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL]): 
19-10-2016 08:35:47.564 UTC Status alarm.cpp:62: sprout issued 1005.4 alarm
19-10-2016 08:35:50.130 UTC Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL]): 
19-10-2016 08:36:05.139 UTC Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL]): 
19-10-2016 08:36:14.907 UTC Status sip_connection_pool.cpp:447: Recycle TCP connection slot 37
19-10-2016 08:36:17.564 UTC Status alarm.cpp:62: sprout issued 1005.4 alarm

**Comment by richardwhiuk** [comment]
This is because there's no configured SNMP IP address, so there's nowhere for Sprout to send the fact that there are no ongoing alarms to. If you have an SNMP receiver, you can configure a `snmp_ip` in shared configuration to prevent this warning, and send alarms, otherwise you can ignore it.

**Comment by leader-us** [comment]
Thanks
