### ISSUE TITLE
Viop client cant register or send a call

### ISSUE THREAD

**Issue by leader-us** [Metaswitch/clearwater-docker#46]
192.168.147.130 is my docker host (public ip)
I can't find any log to resolve this prolem .
response VIOP msg  SIP/2.0 483 Too Many Hops

following is my sip trace logs

2016-10-25 13:47:04.443760 [blink.exe 6024]: SENDING: Packet 38, +0:04:58.165024
192.168.147.1:52584 -(SIP over TCP)-> 192.168.147.130:5060
REGISTER sip:example.com SIP/2.0

Via: SIP/2.0/TCP 192.168.147.1:52584;rport;branch=z9hG4bKPj1a0cf45e646e4d8f9f88b95647093ee9;alias

Max-Forwards: 70

From: "wuzhihui" sip:6505550347@example.com;tag=70809066b7b9417594a10cc28324097a

To: "wuzhihui" sip:6505550347@example.com

Contact: sip:65471038@192.168.147.1:52324;transport=tcp;+sip.instance="urn:uuid:ba6a3e2c-9967-4bad-bdc9-1df857632231"

Call-ID: 8742b45095f44fad9933fec5849c7814

CSeq: 1 REGISTER

Expires: 600

Supported: gruu

User-Agent: Blink 1.4.2 (Windows)

Content-Length:  0
## 

2016-10-25 13:47:04.445205 [blink.exe 6024]: RECEIVED: Packet 39, +0:04:58.166469
192.168.147.130:5060 -(SIP over TCP)-> 192.168.147.1:52584
SIP/2.0 483 Too Many Hops

Via: SIP/2.0/TCP 192.168.147.1:52584;rport=52584;received=172.17.1.1;branch=z9hG4bKPj1a0cf45e646e4d8f9f88b95647093ee9;alias

Call-ID: 8742b45095f44fad9933fec5849c7814

From: "wuzhihui" sip:6505550347@example.com;tag=70809066b7b9417594a10cc28324097a

To: "wuzhihui" sip:6505550347@example.com;tag=z9hG4bKPjms8X0MkttGIw99ToVrtvlzGFmLtQm6ft

CSeq: 1 REGISTER

Content-Length:  0
##

**Comment by leader-us** [comment]
some other logs  from ralf

24-10-2016 16:00:15.330 UTC Error diameterstack.cpp:293: Routing error: 'No remaining suitable candidate to route the message to' for message with Command-Code 271, Destination-Host  and Destination-Realm example.com
24-10-2016 16:00:15.330 UTC Warning peer_message_sender.cpp:125: Failed to send ACR to  (number 0)
24-10-2016 16:00:15.330 UTC Error peer_message_sender.cpp:145: Failed to connect to all CCFs, message not sent
24-10-2016 16:00:15.330 UTC Warning session_manager.cpp:414: Session for 8a6d33ca00b0462c8040f1c9dd90175d received error from CDF
24-10-2016 16:00:28.476 UTC Error diameterstack.cpp:293: Routing error: 'No remaining suitable candidate to route the message to' for message with Command-Code 271, Destination-Host  and Destination-Realm example.com
24-10-2016 16:00:28.477 UTC Warning peer_message_sender.cpp:125: Failed to send ACR to  (number 0)
24-10-2016 16:00:28.477 UTC Error peer_message_sender.cpp:145: Failed to connect to all CCFs, message not sent
24-10-2016 16:00:28.477 UTC Warning session_manager.cpp:414: Session for 361e9c1bb0ed4b73860e1014c51a2cf0 received error from CDF
24-10-2016 16:00:40.501 UTC Error diameterstack.cpp:293: Routing error: 'No remaining suitable candidate to route the message to' for message with Command-Code 271, Destination-Host  and Destination-Realm example.com

**Comment by leader-us** [comment]
sprout resend registry SIP Message to self caused problem 

24-10-2016 20:36:38.303 UTC Verbose sproutletproxy.cpp:1587: noop-0x7f4cf0019390 pass initial request Request msg REGISTER/cseq=1 (tdta0x7f4cf00375d0) to Sproutlet
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:1350: Sproutlet send_request 0x7f4cf0037be0
24-10-2016 20:36:38.303 UTC Verbose sproutletproxy.cpp:1386: noop-0x7f4cf0019390 sending Request msg REGISTER/cseq=1 (tdta0x7f4cf00375d0) on fork 0
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:1750: Processing actions from sproutlet - 0 responses, 1 requests, 0 timers
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:1790: Processing request 0x7f4cf0037678, fork = 0
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:1914: noop-0x7f4cf0019390 transmitting request on fork 0
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:1928: noop-0x7f4cf0019390 store reference to non-ACK request Request msg REGISTER/cseq=1 (tdta0x7f4cf00375d0) on fork 0
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:1742: Removing message 0x7f4cf0037be0 => txdata 0x7f4cf0037678 mapping
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:119: Find target Sproutlet for request
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:158: Found next routable URI: sip:169.169.228.123:5052;transport=TCP;lr;orig
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:329: Possible service name - 169
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:335: Hostname - 169.228.123
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:329: Possible service name - 169
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:335: Hostname - 169.228.123
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:329: Possible service name - 169
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:335: Hostname - 169.228.123
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:329: Possible service name - 169
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:335: Hostname - 169.228.123
24-10-2016 20:36:38.303 UTC Debug sproutletproxy.cpp:874: No local sproutlet matches request
24-10-2016 20:36:38.303 UTC Debug pjsip: tsx0x7f4cf001e Transaction created for Request msg REGISTER/cseq=1 (tdta0x7f4cf00375d0)
24-10-2016 20:36:38.303 UTC Debug basicproxy.cpp:1618: Added trail identifier 71 to UAC transaction
24-10-2016 20:36:38.303 UTC Debug pjutils.cpp:490: Next hop node is encoded in top route header
24-10-2016 20:36:38.303 UTC Debug sipresolver.cpp:86: SIPResolver::resolve for name 169.169.228.123, port 5052, transport 6, family 2
24-10-2016 20:36:38.303 UTC Debug baseresolver.cpp:425: Attempt to parse 169.169.228.123 as IP address
24-10-2016 20:36:38.303 UTC Debug sipresolver.cpp:103: Target is an IP address - default port/transport if required
24-10-2016 20:36:38.303 UTC Info pjutils.cpp:963: Resolved destination URI sip:169.169.228.123:5052;transport=TCP;lr;orig to 1 servers
24-10-2016 20:36:38.303 UTC Debug pjutils.cpp:490: Next hop node is encoded in top route header
24-10-2016 20:36:38.303 UTC Debug basicproxy.cpp:1641: Next hop 169.169.228.123 is not a stateless proxy
24-10-2016 20:36:38.303 UTC Debug basicproxy.cpp:1655: Sending request for sip:example.com
24-10-2016 20:36:38.303 UTC Debug pjsip: tsx0x7f4cf001e Sending Request msg REGISTER/cseq=1 (tdta0x7f4cf00375d0) in state Null
24-10-2016 20:36:38.303 UTC Debug pjsip:       endpoint Request msg REGISTER/cseq=1 (tdta0x7f4cf00375d0): skipping target resolution because address is already set
24-10-2016 20:36:38.303 UTC Verbose common_sip_processing.cpp:136: TX 949 bytes Request msg REGISTER/cseq=1 (tdta0x7f4cf00375d0) to TCP 169.169.228.123:5052:

but can't understand why

**Comment by richardwhiuk** [comment]
Can you provide the full Sprout log you see when this occurs?

**Comment by eleanor-merry** [comment]
Closing as unreproducible.
