### ISSUE TITLE
sprout args error

### ISSUE THREAD

**Issue by leader-us** [Metaswitch/clearwater-docker#47]
if I set IP addr to param  chronos-hostname ,sprout  can't startup
--chronos-hostname=169.169.30.160

**Comment by richardwhiuk** [comment]
What error do you see? What logs does Sprout produce? The issue template which appears when you create an issue via GitHub prompts for these details.

Also, you may find the mailing list a more useful venue for support - issues are better suited when there is a concrete problem at hand.

**Comment by eleanor-merry** [comment]
Closing as unreproducible.
