### ISSUE TITLE
Homestead tries to contact cassandra on localhost

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/clearwater-docker#48]
#### Symptoms

Symptom is that homestead terminates, ellis does not work, and the deployment is DOA. This is on a multi-host deployment, so localhost does not resolve to the cassandra node (although cassandra does).

I'm actually using Kubernetes, but believe that the same issue would occur on multi-host with a pure Docker solution.

#### Impact

Clearwater does not work.

#### Release and environment 

Currently running off the clearwater branch.

#### Steps to reproduce

Install using Kubernetes. Ellis does not work (happy to help with repro).

**Comment by plwhite** [comment]
@richardwhiuk This is the blocking issue I just mentioned to you. I'm about to rebuild all images and update just in case (as you thought was possible) there's an issue that has been fixed recently.

**Comment by richardwhiuk** [comment]
So homestead will only attempt to contact cassandra on localhost, if --cassandra is not passed, which only occurs if cassandra_hostname is not configured in config.

I think this was resolved for Docker by https://github.com/Metaswitch/clearwater-infrastructure/commit/6f6360ce2528e05b087a70ab5570db764fd4c214 - so I think you should just need the latest version of clearwater-auto-config-docker

**Comment by plwhite** [comment]
@richardwhiuk I am not supplying a config file, so does that mean to fix this I have to change the image? If so, what file do I have to change?

**Comment by richardwhiuk** [comment]
The node should automatically configure itself with the correct config. What release are you running? You say you are running of the clearwater branch - what package repository are you using? Stable? When did you build the images?

You should check what cassandra is configured to by inspecting `/etc/clearwater/shared_config` on homestead.

**Comment by plwhite** [comment]
Ouch. My fault - there was some invalid configuration which meant I was picking up an old version of the base image. I'll retest to ensure that fixes things, but the config file is definitely now correct.

Sorry for the confusion
