### ISSUE TITLE
When ellis fails, it reports javascript errors

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/clearwater-docker#51]
#### Symptoms

This was triggered as a side effect of #48. The deployment had got into a broken state where ellis could contact neither homer nor homestead.

Operations on ellis returned javascript errors.

#### Impact

While the deployment was broken anyway, a fundamental issue was being hidden as a browser incompatibility issue. Correct behaviour would have been to return an error page to the subscriber.

#### Release and environment 

Current master release.

#### Steps to reproduce

Repros if ellis cannot contact homer or homestead. Bug #48 would cause that, for example.

**Comment by mirw** [comment]
@plwhite, please can you raise this against Ellis (https://github.com/Metaswitch/ellis/issues), and please can you specify what Javascript errors you see, so that we can debug this?

**Comment by plwhite** [comment]
Closed and replaced with https://github.com/Metaswitch/ellis/issues/195
